#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║     Кодер - MoonMag     ║║      Студия разработки плагинов    ║║  Помощь - stolinxlive   ║
#║   t.me/@MoonMagOffical  ║║         vk.com/spacestudiomine     ║║    t.me/@stolinxlive    ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔══════════════════════════════════════════════════════════════════════════════════════════╗
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║░░██████╗██████╗░░█████╗░░██████╗███████╗░░░░██████╗████████╗██╗░░░██╗██████╗░██╗░█████╗░░║
#║░██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝░░░██╔════╝╚══██╔══╝██║░░░██║██╔══██╗██║██╔══██╗░║
#║░╚█████╗░██████╔╝███████║╚█████╗░█████╗░░░░░╚█████╗░░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░░╚═══██░██╔═══╝░██╔══██║░╚═══██╗██╔══╝░░░░░░╚═══██╗░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░██████╔╝██║░░░░░██║░░██║██████╔╝███████╗░░░██████╔╝░░░██║░░░╚██████╔╝██████╔╝██║╚█████╔╝░║
#║░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚══════╝░░░╚═════╝░░░░╚═╝░░░░╚═════╝░╚═════╝░╚═╝░╚════╝░░║
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚══════════════════════════════════════════════════════════════════════════════════════════╝
#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║        Не забудь        ║║        Наш телеграм канал:         ║║       Наш дискорд       ║
#║    Поставить оценочку)  ║║        t.me/spacestudiomc          ║║    dsc.gg/spacestudiomc ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
SERVER-MOTD:
  Line-1: ""
  Line-2: ""

Custom-Server-Icon:
  Enabled: true
  #64x64, главная директория
  Image: server-icon.png

Maintenance:
  Line-1: ""
  Line-2: ""
  kickmessage: "&cНа сервере технические работы! \n заходите позже"
  allowed-players:
    - Danil777Pro
  enabled: true

messages:
  nopermission: "&cУ вас недостаточно прав"
  reload: "&aУспешная перезагрузка"
  usage: "&fИспользование: &6/spacemotd reload"
  enabledmaintenance: "&fРежим технических работ: &aвключен!"
  disabledmaintenance: "&fРежим технических работ: &cвыключен!"
  alreadyenabled: "&fРежим технических работ уже включен!"
  alreadydisabled: "&fРежим технических работ уже выключен!"