#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║     Кодер - MoonMag     ║║      Студия разработки плагинов    ║║  Помощь - stolinxlive   ║
#║   t.me/@MoonMagOffical  ║║         vk.com/spacestudiomine     ║║    t.me/@stolinxlive    ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔══════════════════════════════════════════════════════════════════════════════════════════╗
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#║░░██████╗██████╗░░█████╗░░██████╗███████╗░░░░██████╗████████╗██╗░░░██╗██████╗░██╗░█████╗░░║
#║░██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝░░░██╔════╝╚══██╔══╝██║░░░██║██╔══██╗██║██╔══██╗░║
#║░╚█████╗░██████╔╝███████║╚█████╗░█████╗░░░░░╚█████╗░░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░░╚═══██░██╔═══╝░██╔══██║░╚═══██╗██╔══╝░░░░░░╚═══██╗░░░██║░░░██║░░░██║██║░░██║██║██║░░██║░║
#║░██████╔╝██║░░░░░██║░░██║██████╔╝███████╗░░░██████╔╝░░░██║░░░╚██████╔╝██████╔╝██║╚█████╔╝░║
#║░╚═════╝░╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚══════╝░░░╚═════╝░░░░╚═╝░░░░╚═════╝░╚═════╝░╚═╝░╚════╝░░║
#║░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░║
#╚══════════════════════════════════════════════════════════════════════════════════════════╝
#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║        Не забудь        ║║        Наш телеграм канал:         ║║       Наш дискорд       ║
#║    Поставить оценочку)  ║║        t.me/spacestudiomc          ║║    dsc.gg/spacestudiomc ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
name: SpaceMotd
version: '1.2'
main: ru.moonmag.SpaceMotd
api-version: '1.16'
author: [ SpaceDev ]
commands:
  spacemotd:
    permission: spacemotd.use

permissions:
  spacemotd.use:
    default: op
